//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita_detalle
    {
        public int idserviciodetalle { get; set; }
        public short sv_id { get; set; }
        public int sv_cant { get; set; }
        public decimal sv_precio { get; set; }
        public decimal sv_importe { get; set; }
        public int sv_cita { get; set; }
    
        public virtual citas citas { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
