//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citas()
        {
            this.notaventa = new HashSet<notaventa>();
        }
    
        public int idcita { get; set; }
        public short ct_empleado { get; set; }
        public short ct_cliente { get; set; }
        public short ct_servicio { get; set; }
        public short ct_cantservicios { get; set; }
        public System.DateTime ct_fecha { get; set; }
        public System.TimeSpan ct_hora { get; set; }
        public short ct_estatus { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual empleados empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notaventa> notaventa { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
