//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estetica_lupitaEntities : DbContext
    {
        public estetica_lupitaEntities()
            : base("name=estetica_lupitaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auditorias> auditorias { get; set; }
        public virtual DbSet<citas> citas { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<notaventa> notaventa { get; set; }
        public virtual DbSet<puestos> puestos { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<notaventa_detalle> notaventa_detalle { get; set; }
    }
}
