//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class notaventa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public notaventa()
        {
            this.notaventa_detalle = new HashSet<notaventa_detalle>();
        }
    
        public int idnotaventa { get; set; }
        public decimal nv_total { get; set; }
        public int nv_cita { get; set; }
        public short nv_cliente { get; set; }
        public short nv_empleado { get; set; }
        public short nv_estatus { get; set; }
    
        public virtual citas citas { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual empleados empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notaventa_detalle> notaventa_detalle { get; set; }
    }
}
