//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class notaventa_detalle
    {
        public int idnotaventa { get; set; }
        public short nvd_servicio { get; set; }
        public decimal nvd_precio { get; set; }
        public short nvd_cantidad { get; set; }
        public short nvd_estatus { get; set; }
    
        public virtual notaventa notaventa { get; set; }
        public virtual servicios servicios { get; set; }
    }
}
